import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006a6a",
        "primary-container": "#00a6a7",
        "on-primary": "#ffffff",
        "on-primary-container": "#003434",
        "primary-fixed-dim": "#5bd9d9",
        "on-primary-fixed-variant": "#004f50",
        "on-surface": "#171d1d",
        "on-surface-variant": "#3d4949",
        "surface": "#f5fafa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff5f4",
        "surface-container": "#e9efee",
        "surface-container-high": "#e4e9e9",
        "surface-container-highest": "#dee4e3",
        "surface-bright": "#f5fafa",
        "surface-dim": "#d5dbda",
        "surface-tint": "#006a6a",
        "background": "#f5fafa",
        "background-surface": "#F7F8FA",
        "outline": "#6c7a79",
        "outline-variant": "#bcc9c9",
        "border-subtle": "#E5E6EB",
        "secondary": "#5b5e68",
        "secondary-container": "#dcdfea",
        "on-secondary-container": "#5f636c",
        "success-mint": "#00A6A7",
        "status-pending": "#FF7D00",
        "status-rejected": "#F53F3F",
        "status-offered": "#00B42A",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary": "#96481c",
        "tertiary-container": "#da7d4c",
        "inverse-surface": "#2c3231",
        "inverse-on-surface": "#ecf2f1",
        "inverse-primary": "#5bd9d9",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-gap": "8px",
        "gutter-sm": "12px",
        "gutter-md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      boxShadow: {
        "card": "0 2px 8px rgba(0, 0, 0, 0.04)",
        "modal": "0 4px 16px rgba(0, 0, 0, 0.08)",
        "bottom": "0 -4px 16px rgba(0, 0, 0, 0.02)",
      },
    },
  },
  plugins: [],
};
export default config;
