// Mock data — fallback when backend is unreachable
// All fields match the real API response format

export const mockUser = {
  code: 200,
  message: "成功",
  data: {
    name: "张三",
    phone: "13800138000",
    email: "zhangsan@example.com",
    title: "高级前端工程师",
    avatar: null,
    profile_completeness: 75,
    summary: "5年前端开发经验，精通 React/TypeScript，主导过多个千万级用户项目",
  },
};

export const mockMessages = [
  {
    id: 1,
    type: "system",
    title: "投递状态更新",
    content: "您投递的【字节跳动 - 高级前端工程师】已被HR查看",
    time: "10分钟前",
    unread: true,
  },
  {
    id: 2,
    type: "hr",
    title: "腾讯HR发来消息",
    content: "您好，看到您投递了我们的前端岗位，方便约个时间聊聊吗？",
    time: "2小时前",
    unread: true,
  },
  {
    id: 3,
    type: "system",
    title: "简历推荐",
    content: "您的简历本周被 12 家企业搜索到，曝光率提升了 30%",
    time: "昨天 14:30",
    unread: false,
  },
  {
    id: 4,
    type: "offer",
    title: "面试邀请",
    content: "【阿里巴巴】邀请您参加前端工程师岗位面试，时间：2025-02-20 10:00",
    time: "昨天 09:15",
    unread: false,
  },
  {
    id: 5,
    type: "system",
    title: "收藏提醒",
    content: "您收藏的【拼多多 - 前端技术专家】岗位有新动态",
    time: "2天前",
    unread: false,
  },
];

export const mockJobs = {
  code: 200,
  message: "成功",
  data: {
    items: [
      {
        id: 1,
        title: "高级前端工程师",
        company: "字节跳动",
        location: "北京·海淀区",
        salary_min: 35000,
        salary_max: 60000,
        job_type: "full-time",
        work_mode: "hybrid",
        experience: "3-5年",
        badge: "急聘",
      },
      {
        id: 2,
        title: "React Native 开发工程师",
        company: "腾讯",
        location: "深圳·南山区",
        salary_min: 30000,
        salary_max: 50000,
        job_type: "full-time",
        work_mode: "onsite",
        experience: "3-5年",
        badge: "新",
      },
      {
        id: 3,
        title: "前端架构师",
        company: "阿里巴巴",
        location: "杭州·余杭区",
        salary_min: 45000,
        salary_max: 75000,
        job_type: "full-time",
        work_mode: "remote",
        experience: "5-10年",
      },
      {
        id: 4,
        title: "产品设计师",
        company: "小红书",
        location: "上海·黄浦区",
        salary_min: 25000,
        salary_max: 45000,
        job_type: "full-time",
        work_mode: "hybrid",
        experience: "1-3年",
      },
      {
        id: 5,
        title: "全栈工程师",
        company: "美团",
        location: "北京·朝阳区",
        salary_min: 30000,
        salary_max: 55000,
        job_type: "full-time",
        work_mode: "onsite",
        experience: "3-5年",
        badge: "热招",
      },
      {
        id: 6,
        title: "前端实习生",
        company: "百度",
        location: "北京·海淀区",
        salary_min: 8000,
        salary_max: 12000,
        job_type: "internship",
        work_mode: "onsite",
        experience: "应届/实习",
      },
    ],
    total: 6,
  },
};
